// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Dcchh4ffJFlrQWfRLiQdoslI8bwHG-Y',
    appId: '1:178336795272:web:149d8553777c2d6351ad3d',
    messagingSenderId: '178336795272',
    projectId: 'minchir-haftalik-program',
    authDomain: 'minchir-haftalik-program.firebaseapp.com',
    storageBucket: 'minchir-haftalik-program.firebasestorage.app',
    measurementId: 'G-SYCTMWLTZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4wrfewLXzuZytonTXYrkEwbfwU33q0BE',
    appId: '1:178336795272:android:26f9fbcbf32f3a6f51ad3d',
    messagingSenderId: '178336795272',
    projectId: 'minchir-haftalik-program',
    storageBucket: 'minchir-haftalik-program.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1KJCi_nFlvbKkx6nXfGlLMXJINKNQL28',
    appId: '1:178336795272:ios:5113446c4363761751ad3d',
    messagingSenderId: '178336795272',
    projectId: 'minchir-haftalik-program',
    storageBucket: 'minchir-haftalik-program.firebasestorage.app',
    iosBundleId: 'com.example.ldeadTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1KJCi_nFlvbKkx6nXfGlLMXJINKNQL28',
    appId: '1:178336795272:ios:5113446c4363761751ad3d',
    messagingSenderId: '178336795272',
    projectId: 'minchir-haftalik-program',
    storageBucket: 'minchir-haftalik-program.firebasestorage.app',
    iosBundleId: 'com.example.ldeadTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3Dcchh4ffJFlrQWfRLiQdoslI8bwHG-Y',
    appId: '1:178336795272:web:97b1b1409e1907be51ad3d',
    messagingSenderId: '178336795272',
    projectId: 'minchir-haftalik-program',
    authDomain: 'minchir-haftalik-program.firebaseapp.com',
    storageBucket: 'minchir-haftalik-program.firebasestorage.app',
    measurementId: 'G-R7F1XTSWW4',
  );
}
